addon-name: "Libs - Keystone Roulette"
addon-description: "randomizes Mythic+ keystone selection"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/libs-keystoneroulette"
  discord: "https://discord.gg/Qc9TRBv"
